### ISSUE TITLE
Upgrade extension to Visual Studio 2019 

### ISSUE THREAD

**Issue by rmaziarka** [cezarypiatek/DDDToolbox#6]
Hello Cezary,

Unfortunately, the extension is not working with Visual Studio 2019. Could you provide a version for this VS?

**Comment by cezarypiatek** [comment]
Hi,

Thanks for reporting this issue. I've just updated extension's manifest to support newer versions than 2017. Pleas check out the new release https://marketplace.visualstudio.com/items?itemName=54748ff9-45fc-43c2-8ec5-cf7912bc3b84.DDToolbox

**Comment by rmaziarka** [comment]
I don't know why, but I still get this error. I installed your second extension without problem, but DDDToolbox get:
![image](https://user-images.githubusercontent.com/5219374/56724322-0e33e180-674b-11e9-8642-3da4480525e6.png)

**Comment by cezarypiatek** [comment]
Oh I'm sorry, I don't know why but the vsix link in marketplace wasn't updated. Please try again.

**Comment by rmaziarka** [comment]
It works :) thanks for help.
